# docker-compose
version: '3'
services:
  # infrastructure
  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
